name: mindful
description: Your Ultimate Companion for Focus and Well-being.
homepage: https://github.com/akaMrNagar/Mindful
publish_to: "none"
version: 1.2.0+120

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Runtime dependencies
  # UI
  fluentui_system_icons: ^1.1.210
  fl_chart: ^0.63.0
  flutter_heatmap_calendar: ^1.0.5
  animated_flip_counter: ^0.3.4
  flutter_confetti: ^0.3.0
  smooth_page_indicator: ^1.2.0+3
  dynamic_color: ^1.7.0

  # Animation
  flutter_animate: ^4.2.0+1
  skeletonizer: ^1.4.1+1

  # Database and Storage
  path: ^1.9.0
  path_provider: ^2.1.2
  file_picker: ^8.0.7
  sqlite3: ^2.4.5
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Util
  intl: ^0.19.0
  sliver_tools: ^0.2.12
  flutter_riverpod: ^2.5.1
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Development dependencies.
  # Generator =>  dart run build_runner build
  build_runner: ^2.4.11
  flutter_lints: ^2.0.0
  drift_dev: ^2.18.0
  isar_generator: ^3.1.0+1


# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Onboarding
    - assets/illustrations/onboarding_1.png
    - assets/illustrations/onboarding_2.png
    - assets/illustrations/onboarding_3.png
    - assets/illustrations/onboarding_4.png

    # Short content platform's icons
    - assets/icons/instaReels.png
    - assets/icons/fbReels.png
    - assets/icons/snapSpotlight.png
    - assets/icons/ytShorts.png
    - assets/icons/redditShorts.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
